apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
    type: mvc
spec:
  containers:
    - name: app-mvc
      image: escdocker2001/mvcprototipo:latest
      ports:
        - containerPort: 80
      env:
        - name: ConnectionStrings__ContextoCurso
          value: Server=mssql-service;Database=CursosOnline;User=sa;Password=$RobertoRoman2025